### ISSUE TITLE
Font color issues

### ISSUE THREAD

**Issue by yungamiro** [ElijahPepe/BetterDiscordAddons#3]
I dunno if it's for everyone or just me but when you hover on a discord server, the server name and the the popup background are the same which results in an invisible font

**Comment by MicSup08** [comment]
yeah i've been having this as well:

![2](https://user-images.githubusercontent.com/38831587/112878696-27283880-90c0-11eb-9ca2-e91a7493c50a.png)

oddly enough, hovering over a folder works normally:

![3](https://user-images.githubusercontent.com/38831587/112878913-5fc81200-90c0-11eb-9e0a-a6f381b767f5.png)

**Comment by yungamiro** [comment]
Any update soon?

**Comment by yungamiro** [comment]
![IVt0X9T](https://user-images.githubusercontent.com/78366053/112886577-68294880-90d2-11eb-9334-7a21a2955c1f.png)
Update /!\ 
Screen sharing / Streaming in a server

**Comment by Persea-gatuna** [comment]
Having the same issue
![image](https://user-images.githubusercontent.com/57922140/112939959-c2420200-9102-11eb-8d08-fedfaf5126b6.png)

But hovering over a folder works just fine
![image](https://user-images.githubusercontent.com/57922140/112940002-db4ab300-9102-11eb-966f-62db396dcfc8.png)

**Comment by T4H5iN** [comment]
**Could it be more transparent when I got mentioned or replied?**
![image](https://user-images.githubusercontent.com/77932280/114269397-a6a2f980-9a28-11eb-9a7e-c2608024f1f8.png)

**Comment by ElijahPepe** [comment]
I'd like to personally apologize here, this is 100% my fault and I've been incredibly busy over the last few months and haven't been able to get to this. This is completely irresponsible of me and I've alienated a lot of people's trust through this issue. That sounds copy and paste, but it's genuine as I can be.

I'm going to work on trying to get this fixed right now. I thought I fixed it, but clearly I have a lot of work to do. I started this project as a passion and it's incredibly troubling for me to see that I've done this to a lot of people. That's not something I want to do.

This is something that I desperately couldn't fix on my own; every time that I got to it I felt that I was putting a lot of strain on my back and it was going to eventually be something that broke my own back. I can see that I should have prioritized this a lot more than I did, and now a lot of people don't like it. The new Discord rebrand will probably change this so I've hopped onto this discussion at a good time.

Rest assured I'm a. still alive, and b. still going to keep working on this. This was something that I thought would be a one and done deal, but clearly I've made a mistake and I can't apologize enough for being so late with it.

It's currently late at night while I'm writing this, as of Saturday, May 15, 2021, but I can start work tomorrow. I'm going to apologize right here and now, and I hope that you accept it. Currently I think I have a good fix for the issue, but there's a bigger issue of adding things onto the CSS that people won't be able to get updated with. I want to improve this, because it's choppy and that's not really what I want to do. I don't like to see people upset, and it was my own negligence that literally caused people to be upset when I could have just been more responsible.

This is strong coming from someone who develops _BetterDiscord themes_ of all things, but I try to be as open as I can and I didn't do that. That's my fault and my fault alone. I ignored people, focused on my work, and treated life like I've done for a while. That's a problem, and fortunately I've addressed it here.

Right now I think I have a fix in place so give GitHub 10 minutes and it should work. If it doesn't, then you can leave a comment here.

**Comment by brenmadeit** [comment]
Im sorry I dont understand about this, how to do I update to your fixed version for this issue?

**Comment by ElijahPepe** [comment]
> 
> 
> Im sorry I dont understand about this, how to do I update to your fixed version for this issue?

BD will update automatically within 10 minutes of a commit.

**Comment by brenmadeit** [comment]
> h
Nothing happened for mine tho, anything I can do manually to fix this issue?

**Comment by CalamiTheLarge** [comment]
> 
> 
> I'd like to personally apologize here, this is 100% my fault and I've been incredibly busy over the last few months and haven't been able to get to this. This is completely irresponsible of me and I've alienated a lot of people's trust through this issue. That sounds copy and paste, but it's genuine as I can be.
> 
> I'm going to work on trying to get this fixed right now. I thought I fixed it, but clearly I have a lot of work to do. I started this project as a passion and it's incredibly troubling for me to see that I've done this to a lot of people. That's not something I want to do.
> 
> This is something that I desperately couldn't fix on my own; every time that I got to it I felt that I was putting a lot of strain on my back and it was going to eventually be something that broke my own back. I can see that I should have prioritized this a lot more than I did, and now a lot of people don't like it. The new Discord rebrand will probably change this so I've hopped onto this discussion at a good time.
> 
> Rest assured I'm a. still alive, and b. still going to keep working on this. This was something that I thought would be a one and done deal, but clearly I've made a mistake and I can't apologize enough for being so late with it.
> 
> It's currently late at night while I'm writing this, as of Saturday, May 15, 2021, but I can start work tomorrow. I'm going to apologize right here and now, and I hope that you accept it. Currently I think I have a good fix for the issue, but there's a bigger issue of adding things onto the CSS that people won't be able to get updated with. I want to improve this, because it's choppy and that's not really what I want to do. I don't like to see people upset, and it was my own negligence that literally caused people to be upset when I could have just been more responsible.
> 
> This is strong coming from someone who develops _BetterDiscord themes_ of all things, but I try to be as open as I can and I didn't do that. That's my fault and my fault alone. I ignored people, focused on my work, and treated life like I've done for a while. That's a problem, and fortunately I've addressed it here.
> 
> Right now I think I have a fix in place so give GitHub 10 minutes and it should work. If it doesn't, then you can leave a comment here.

It doesn't seem to be fixed, is there a manual thing i can do in the settings to change the text colour or the background of hovering over server icons?

**Comment by ghost** [comment]
As Calami said, still an issue.
I'm no CSS expert, but I think the issue is that the background colour of the tooltip and the font colour are set to the same variable.
Probably just need to change the background colour, since all the other text seems to use the same colour as that.
EG of darker pinks
![image](https://user-images.githubusercontent.com/11553364/133256896-d1db5afd-526d-4d26-8b20-041ae5847231.png)

I toned down the "pink" of being mentioned too, that was way too bright for me, and made the folder background colour grey instead of black so it's visible.

EG of grey background for folders / header bars on popups, etc.
![image](https://user-images.githubusercontent.com/11553364/133256834-9a2a02a2-bd3d-4740-83e3-5e57e7287a8c.png)

Actual values if you like em: 
```css
:root {
    --color-high: rgb(51, 51, 51);
    --color-lowest: rgb(255, 255, 255);
    --color-low: rgb(184, 217, 209);
    --color-mid: rgb(122, 153, 145);
    --color-alert: rgb(118, 0, 39);
    --color-alert-hover: rgb(154, 0, 51);
    --color-high-trans: rgba(0, 0, 0, 0.8);
    --color-low-trans: rgba(184, 217, 209, 0.6);
    --color-alert-trans: rgba(229, 0, 77, 0.7);
    --font: BlenderProBold;
}
```

**Comment by CalamiTheLarge** [comment]
> 
> 
> As Calami said, still an issue.
> I'm no CSS expert, but I think the issue is that the background colour of the tooltip and the font colour are set to the same variable.
> Probably just need to change the background colour, since all the other text seems to use the same colour as that.
> EG of darker pinks
> ![image](https://user-images.githubusercontent.com/11553364/133256896-d1db5afd-526d-4d26-8b20-041ae5847231.png)
> 
> I toned down the "pink" of being mentioned too, that was way too bright for me, and made the folder background colour grey instead of black so it's visible.
> 
> EG of grey background for folders / header bars on popups, etc.
> ![image](https://user-images.githubusercontent.com/11553364/133256834-9a2a02a2-bd3d-4740-83e3-5e57e7287a8c.png)
> 
> Actual values if you like em:
> 
> ```css
> :root {
>     --color-high: rgb(51, 51, 51);
>     --color-lowest: rgb(255, 255, 255);
>     --color-low: rgb(184, 217, 209);
>     --color-mid: rgb(122, 153, 145);
>     --color-alert: rgb(118, 0, 39);
>     --color-alert-hover: rgb(154, 0, 51);
>     --color-high-trans: rgba(0, 0, 0, 0.8);
>     --color-low-trans: rgba(184, 217, 209, 0.6);
>     --color-alert-trans: rgba(229, 0, 77, 0.7);
>     --font: BlenderProBold;
> }
> ```

I tried what your code said and it didnt fix the individual servers having just a block colour on a mouse hover, i made the color low have a 0.8 at the end and while it dims the text a bit it does allow you to read the server names, not the best fix but after 30 mins of fiddling its all i got as a solution until someone else who actually knows css can do something about it

**Comment by ghost** [comment]
> i made the color low have a 0.8

Nice. That was clever. That works for now, I like the theme other than that and the pinks being too bright :)

**Comment by ElijahPepe** [comment]
This could work. Feel free to make a PR and I'll merge.

**Comment by brenmadeit** [comment]
> As Calami said, still an issue.
> I'm no CSS expert, but I think the issue is that the background colour of the tooltip and the font colour are set to the same variable.
> Probably just need to change the background colour, since all the other text seems to use the same colour as that.
> EG of darker pinks
> ![image](https://user-images.githubusercontent.com/11553364/133256896-d1db5afd-526d-4d26-8b20-041ae5847231.png)
> 
> I toned down the "pink" of being mentioned too, that was way too bright for me, and made the folder background colour grey instead of black so it's visible.
> 
> EG of grey background for folders / header bars on popups, etc.
> ![image](https://user-images.githubusercontent.com/11553364/133256834-9a2a02a2-bd3d-4740-83e3-5e57e7287a8c.png)
> 
> Actual values if you like em:
> 
> ```css
> :root {
>     --color-high: rgb(51, 51, 51);
>     --color-lowest: rgb(255, 255, 255);
>     --color-low: rgb(184, 217, 209);
>     --color-mid: rgb(122, 153, 145);
>     --color-alert: rgb(118, 0, 39);
>     --color-alert-hover: rgb(154, 0, 51);
>     --color-high-trans: rgba(0, 0, 0, 0.8);
>     --color-low-trans: rgba(184, 217, 209, 0.6);
>     --color-alert-trans: rgba(229, 0, 77, 0.7);
>     --font: BlenderProBold;
> }
> ```

how should I change the color tho
